# Sample configuration for fortio-cli
# Global default duration for all tests (e.g., "60s"). If omitted, defaults to 5s per run.
duration: 60s
# Define one or more Fortio tests under the "tests" array. You may override duration per test.
tests:
  - name: example_http
    url: https://www.example.com
    qps: 10
    concurrency: 2
    duration: 30s # optional per-test override
    headers:
      User-Agent: fortio-cli/1.0
      Accept: application/json
    jitter: true # enable +/-10% jitter
    uniform: false # disable uniform staggering between threads
